name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t myapp:latest .

    - name: Push Docker Image
      run: |
        docker tag myapp:latest myregistry/myapp:latest
        docker push myregistry/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      
    - name: Apply Kubernetes Config
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
